### ISSUE TITLE
Error fetching credentials from aws profiles file (0.16.4 -> 0.20.0)

### ISSUE THREAD

**Issue by piotr-yuxuan** [BrunoBonacci/1config#31]
Hello,

I've been happily using this tool for some time and usually it has worked quite well. However today I've bumped the version from 0.16.4 to 0.20.0 in some project, with all surrounding code and 1cfg remote state staying the same. In 0.16.4 I get the config value I expect, however in 0.20.0 I stumble upon this error:

``` log
2021-01-12 12:23:34.623 [async-thread-macro-2] ERROR
                cognitect.aws.credentials - Error fetching credentials from aws profiles file
clojure.lang.ExceptionInfo: Invalid format in config
	at cognitect.aws.config$parse$fn__33508.invoke(config.clj:84)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at cognitect.aws.config$parse.invokeStatic(config.clj:68)
	at cognitect.aws.config$parse.invoke(config.clj:62)
	at cognitect.aws.credentials$profile_credentials_provider$reify__33804.fetch(credentials.clj:234)
	at cognitect.aws.credentials$refresh_BANG_.invokeStatic(credentials.clj:62)
	at cognitect.aws.credentials$refresh_BANG_.invoke(credentials.clj:48)
	at cognitect.aws.credentials$cached_credentials_with_auto_refresh$reify__33778.fetch(credentials.clj:96)
	at cognitect.aws.credentials$chain_credentials_provider$reify__33792$fn__33793.invoke(credentials.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2701)
	at clojure.core$some.invoke(core.clj:2692)
	at cognitect.aws.credentials$chain_credentials_provider$reify__33792.fetch(credentials.clj:150)
	at cognitect.aws.credentials$fn__33735$G__33731__33737.invoke(credentials.clj:20)
	at cognitect.aws.credentials$fn__33735$G__33730__33740.invoke(credentials.clj:20)
	at cognitect.aws.util$fetch_async$fn__33259$fn__33260.invoke(util.clj:297)
	at cognitect.aws.util$fetch_async$fn__33259.invoke(util.clj:296)
	at clojure.core.async$thread_call$fn__7663.invoke(async.clj:484)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

This prevents me from upgrading to a more recent version. Any advice?

Piotr

**Comment by BrunoBonacci** [comment]
Hi Piotr,

Please NOTE that the v0.20.0 introduces a BREAKING CHANGES, unfortunate but necessary.
https://cljdoc.org/d/com.brunobonacci/oneconfig/0.20.0/doc/changelog

After a long time trying to compile the `aws-encryption-sdk` to native and failing, I've decided to drop `amazonica` in favour of `congnitect/aws-api` and use the KMS api directly without `aws-encryption-sdk`.
Unfortunately `aws-encryption-sdk` uses a proprietary binary format which I didn't feel it useful to replicate, therefore the stored config use a different format which is just the output of the KMS encryption API.

In order to use the new version, please make sure that you follow the steps for the [*one-time migration*](https://cljdoc.org/d/com.brunobonacci/oneconfig/0.20.0/doc/user-guides/migration-procedure) and update all the clients.

Now your error seems to come from the `congnitect/aws-api` while reading the credentials.
It could be that your credentials file is still using the old AWS format.
Please make sure your aws credentials files look like as following:
https://docs.aws.amazon.com/credref/latest/refdocs/file-format.html

**Comment by piotr-yuxuan** [comment]
Ha yeah, I didn't see that breaking change. So the solution is to update to 0.17.0 and then think about if and when doing the migration. Cheers :-)

**Comment by BrunoBonacci** [comment]
that's correct, however, I still think that there is an issue with the format of you `~/.aws/config,credentials` files which you will need to fix as well.
